variables:
    IMAGE: dbmat-angular-k8s-prod
    VERSION: "1.0"

include:
 - project : 'ci-tools/container-image-ci-templates'
   file : 'kaniko-image.gitlab-ci.yml'
   ref: master

stages:
 - build_docker_image

build_container_job:
 rules:
  - if: $DO_DOCKER_IMAGE == "yes" && $CI_PIPELINE_SOURCE != 'merge_request_event' 
 stage: build_docker_image
 extends: .build_kaniko
 variables:
  REGISTRY_IMAGE_PATH : "registry.cern.ch/dbmat/$IMAGE:$VERSION"
  CONTEXT_DIR: ""
  PUSH_IMAGE: "true"
  DOCKER_FILE_NAME: "Dockerfile"
